In [2]:
import numpy as np

In [4]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
A.shape

(3, 2)

In [13]:
n_rows = A.shape[0]
n_rows

3

In [15]:
%pwd

'/home/yann/machine-learning/intro'

In [20]:
%cd ~

/home/yann


In [22]:
%pwd

'/home/yann'

In [25]:
%ls

Desktop/    Downloads/     machine-learning/  Pictures/   Public/     venv/
Documents/  featuresX.dat  Music/             priceY.dat  Templates/  Videos/


In [29]:
featuresX = np.loadtxt('featuresX.dat')
priceY = np.loadtxt('priceY.dat')

In [31]:
dir()

['A',
 'In',
 'Out',
 '_',
 '_12',
 '_13',
 '_14',
 '_15',
 '_18',
 '_21',
 '_22',
 '_26',
 '_30',
 '_4',
 '_5',
 '_6',
 '_8',
 '_9',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_dh',
 '_exit_code',
 '_i',
 '_i1',
 '_i10',
 '_i11',
 '_i12',
 '_i13',
 '_i14',
 '_i15',
 '_i16',
 '_i17',
 '_i18',
 '_i19',
 '_i2',
 '_i20',
 '_i21',
 '_i22',
 '_i23',
 '_i24',
 '_i25',
 '_i26',
 '_i27',
 '_i28',
 '_i29',
 '_i3',
 '_i30',
 '_i31',
 '_i4',
 '_i5',
 '_i6',
 '_i7',
 '_i8',
 '_i9',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 '_sh',
 'exit',
 'featuresX',
 'get_ipython',
 'n_rows',
 'np',
 'priceY',
 'quit',
 'sz']

In [33]:
featuresX.shape

(4, 2)

In [34]:
del featuresX

In [35]:
featuresX

NameError: name 'featuresX' is not defined

In [41]:
v = priceY[1:10]

In [42]:
v

array([ 3999.,  3690.,  2320.])

In [58]:
np.save?

In [53]:
np.save('v', v)  # extension '.npy' added automatically

In [54]:
%ls

Desktop/    featuresX.dat      Pictures/   Templates/  v.npy
Documents/  machine-learning/  priceY.dat  venv/       v.save.npy
Downloads/  Music/             Public/     Videos/


In [59]:
np.load('v.npy')

array([ 3999.,  3690.,  2320.])

In [80]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [81]:
A[2,1]  # index starts at 0

6

In [82]:
A[:,1]

array([2, 4, 6])

In [83]:
A[0]

array([1, 2])

In [84]:
A[0] = np.array([8, 9])

In [85]:
A

array([[8, 9],
       [3, 4],
       [5, 6]])

In [91]:
B = np.array([[10, 11], [12, 13]])
B

array([[10, 11],
       [12, 13]])

In [93]:
np.concatenate([A, B])

array([[ 8,  9],
       [ 3,  4],
       [ 5,  6],
       [10, 11],
       [12, 13]])